version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
    api:
        build: .
        env_file: ./api/.env
        environment:
            POSTGRES_HOST: db
        depends_on:
            - db
        ports:
            - '3000:3000'